# Streamlit Secrets - Werden in der Cloud-Version benötigt
# Diese Datei wird auf Streamlit Cloud automatisch mit Ihren dort gespeicherten Secrets überschrieben

[server]
enableXsrfProtection = false
enableCORS = false